name: Release Builds
on:
  push:
    tags:
      - 'v*'
  workflow_call:
  workflow_dispatch:

env:
  SCONS_FLAGS: production=yes
  SCONS_CACHE_MSVC_CONFIG: true
  PYTHONIOENCODING: utf8

jobs:
  build:
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
            platform: linuxbsd
            archive-name: linux
            cache-name: release-linux-editor
            bin: ./bin/godot.linuxbsd.editor.x86_64

          - runner: windows-latest
            platform: windows
            archive-name: win64.exe
            cache-name: release-windows-editor
            bin: ./bin/godot.windows.editor.x86_64.exe

    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup dependencies
        if: matrix.platform == 'linuxbsd'
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-bin  # TODO: Figure out somehow how to embed this one.
          if [ "${{ matrix.proj-test }}" == "true" -o "${{ matrix.proj-export }}" == "true" ]; then
            sudo apt-get install mesa-vulkan-drivers
          fi

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download pre-built ANGLE
        if: matrix.platform != 'linuxbsd'
        shell: sh
        id: angle-sdk
        run: |
          if python ./misc/scripts/install_angle.py; then
            echo "ANGLE_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::ANGLE SDK installation failed, building without ANGLE support."
            echo "ANGLE_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Download Direct3D 12 SDK components
        if: matrix.platform == 'windows'
        shell: sh
        id: d3d12-sdk
        run: |
          if python ./misc/scripts/install_d3d12_sdk_windows.py; then
            echo "D3D12_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Windows: Direct3D 12 SDK installation failed, building without Direct3D 12 support."
            echo "D3D12_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi
        continue-on-error: true

      - name: Download pre-built AccessKit
        shell: sh
        id: accesskit-sdk
        run: |
          if python ./misc/scripts/install_accesskit.py; then
            echo "ACCESSKIT_ENABLED=yes" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::AccessKit SDK installation failed, building without AccessKit support."
            echo "ACCESSKIT_ENABLED=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Compilation
        if: matrix.platform == 'linuxbsd'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }}
          platform: ${{ matrix.platform }}
          target: editor

      - name: Compilation
        if: matrix.platform == 'windows'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }} d3d12=${{ steps.d3d12-sdk.outputs.D3D12_ENABLED }} accesskit=${{ steps.accesskit-sdk.outputs.ACCESSKIT_ENABLED }} angle=${{ steps.angle-sdk.outputs.ANGLE_ENABLED }}
          platform: ${{ matrix.platform }}
          target: editor

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Prepare artifact
        if: matrix.platform == 'linuxbsd'
        run: |
          rm -rf ./bin/build_deps
          strip bin/godot.*
          chmod +x bin/godot.*
          mv ${{ matrix.bin }} bin/Prodot-${{ github.ref_name }}_${{ matrix.archive-name }}

      - name: Prepare artifact
        if: matrix.platform == 'windows'
        run: |
          Remove-Item bin/build_deps -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
          Move-Item ${{ matrix.bin }} "bin/Prodot-${{ github.ref_name }}_${{ matrix.archive-name }}"

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: Prodot-${{ github.ref_name }}_${{ matrix.archive-name }}
          path: bin/Prodot-${{ github.ref_name }}_${{ matrix.archive-name }}
